// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVsAIQkdo5oqEPSULomQ3A6eGOyWVrJE8',
    appId: '1:682676990501:web:81ccfaa76453eb0a92c5cc',
    messagingSenderId: '682676990501',
    projectId: 'chat-app-e22a6',
    authDomain: 'chat-app-e22a6.firebaseapp.com',
    storageBucket: 'chat-app-e22a6.appspot.com',
    measurementId: 'G-9BJQSTY162',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy4eeovo-qPjulmiDlcyaGl5frZteFACw',
    appId: '1:682676990501:android:aa011a4fb34bf46292c5cc',
    messagingSenderId: '682676990501',
    projectId: 'chat-app-e22a6',
    storageBucket: 'chat-app-e22a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqUVAznDoGIyBvXFciZvLLcmy2VAIul0s',
    appId: '1:682676990501:ios:2bfbf66d01a0d1c692c5cc',
    messagingSenderId: '682676990501',
    projectId: 'chat-app-e22a6',
    storageBucket: 'chat-app-e22a6.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqUVAznDoGIyBvXFciZvLLcmy2VAIul0s',
    appId: '1:682676990501:ios:33dcf9dcc0ca523b92c5cc',
    messagingSenderId: '682676990501',
    projectId: 'chat-app-e22a6',
    storageBucket: 'chat-app-e22a6.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
